compress uncompress:compress.cpp uncompress.cpp bundle.cpp 
	@g++ -std=c++11 -o compress compress.cpp bundle.cpp -g
	@g++ -std=c++11 -o uncompress uncompress.cpp bundle.cpp -g	
.PHONY:clean
clean:
	@rm -rf compress uncompress
